In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

In [3]:
trainX = (x_train/255).reshape(60000, 28*28)

In [4]:
trainX.shape

(60000, 784)

In [5]:
arr = np.array([np.zeros(10) for i in y_train])
for i, value in enumerate(y_train):
    arr[i, value] = 1

In [6]:
arr

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [7]:
trainY = arr
trainY


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [8]:
class MyOutputLayer:
    def __init__(self, inputNeurons, outputNeuronsCount, activationFunction=tf.keras.activations.sigmoid):
        self.inputNeurons = inputNeurons
        self.inputNeuronsCount = inputNeurons.size
        self.outputNeuronsCount = outputNeuronsCount
        self.activationMatrix = np.random.rand(outputNeuronsCount, self.inputNeuronsCount)
        self.biases = np.random.rand(self.outputNeuronsCount)
        self.activationFunction = activationFunction
        self.loss = None
    
    def predict(self, inputNeurons=None):
        #we calculate the dot product of the weights matrix and the input neuron activations array
        t1 = np.dot(self.activationMatrix, inputNeurons if inputNeurons is not None else self.inputNeurons)
        #we add the biases
        t2 = np.add(t1, self.biases)
        #normalize the result with it's largest value
        t3 = t2/t2.max()
        #we run the result through the activation function
        t4 = tf.constant(t3, dtype = tf.float64)
        outputNeurons = self.activationFunction(t3).numpy()
        return outputNeurons

    def backPropagate(self, inputNeurons, expectedOutput):
        prediction = self.predict(inputNeurons)
        difference = np.add(prediction, -1 * expectedOutput)
        loss=np.average(difference)
        self.loss=loss
        return difference
    
    

In [9]:
lo=MyOutputLayer(trainX[0], 10)

In [10]:
lo.predict(trainX[0])

array([0.73096583, 0.71545898, 0.71250224, 0.71176999, 0.71502977,
       0.73105858, 0.72116481, 0.69500566, 0.71051086, 0.70097675])

In [11]:
lo.backPropagate(trainX[0], trainY[0])

array([ 0.73096583,  0.71545898,  0.71250224,  0.71176999,  0.71502977,
       -0.26894142,  0.72116481,  0.69500566,  0.71051086,  0.70097675])

In [13]:
for i, value in enumerate(trainY):
    completionRate = "{:.2f}".format(((i+1)/trainY.size)*1000)
    print(f'Completion: {completionRate}%  | loss: {lo.loss}', end='' )
    lo.backPropagate(trainX[i], trainY[i])
    print(end='\r')
print(f'final loss: {lo.loss}')

final loss: 0.6131140001380405
